extend type Query {
  """
  Reference data. Usually an internal ID or code mapped to a human readable description.
  Mostly static, but will change occasionally.
  NOTE: no auth is required for querying, as the data is public domain.
  """
  referenceData: ReferenceData
}
