type ReferenceData {
  """
  Mapping of country codes to the currency bank payments to that country must be made in.
  In most cases this will be GB/GBP, but for international payments the correct country
  code and currency pair must be used when validating or submitting bank details.
  """
  countriesCurrencies: [CountryCurrency!]

  """
  The possible Legal Statuses of a business.
  """
  legalStatuses: [ReferenceDatum!]
}

type CountryCurrency {
  """
  Country code. For example, 'GB', 'IE', 'PT'.
  """
  code: String!

  """
  Currency code for bank payments to that country. For example, 'GBP', 'EUR'.
  """
  currency: String!
}

"""
Represents the simple code & description of each reference data item.
"""
type ReferenceDatum {
  """
  The code for this item
  """
  code: Int!

  """
  The description for this item
  """
  description: String!
}
