/*
 *
 * Log codes
 * Format: <SERVICE NAME>_<LOG GROUP>_<LOG SUB GROUP>_<CODE>
 */

export const DAL_REQUEST_AUTHENTICATION_001 = 'DAL_REQUEST_AUTHENTICATION_001'
export const DAL_APPLICATION_REQUEST_001 = 'DAL_APPLICATION_REQUEST_001'
export const DAL_APPLICATION_RESPONSE_001 = 'DAL_APPLICATION_RESPONSE_001'
export const DAL_UNHANDLED_ERROR_001 = 'DAL_UNHANDLED_ERROR_001'
export const DAL_RESOLVERS_BUSINESS_001 = 'DAL_RESOLVERS_BUSINESS_001'
export const DAL_HEALTH_CHECK_001 = 'DAL_HEALTH_CHECK_001'

export const RURAL_PAYMENTS_API_REQUEST_001 = 'RURAL_PAYMENTS_API_REQUEST_001'
export const RURAL_PAYMENTS_API_NOT_FOUND_001 = 'RURAL_PAYMENTS_API_NOT_FOUND_001'

// FIXME: are these still used!?
export const RURAL_PAYMENTS_API_ERROR_001 = 'RURAL_PAYMENTS_API_ERROR_001'
export const RURAL_PAYMENTS_API_ACCESS_DENIED_001 = 'RURAL_PAYMENTS_API_ACCESS_DENIED_001'
