/*
 *
 * Log codes
 * Format: <SERVICE NAME>_<LOG GROUP>_<LOG SUB GROUP>_<CODE>
 */

export const DAL_REQUEST_AUTHENTICATION_001 = 'DAL_REQUEST_AUTHENTICATION_001'
export const DAL_APPLICATION_REQUEST_001 = 'DAL_APPLICATION_REQUEST_001'
export const DAL_APPLICATION_RESPONSE_001 = 'DAL_APPLICATION_RESPONSE_001'
export const DAL_UNHANDLED_ERROR_001 = 'DAL_UNHANDLED_ERROR_001'
export const DAL_RESOLVERS_BUSINESS_001 = 'DAL_RESOLVERS_BUSINESS_001'
export const DAL_HEALTH_CHECK_001 = 'DAL_HEALTH_CHECK_001'

export const RURALPAYMENTS_API_REQUEST_001 = 'RURALPAYMENTS_API_REQUEST_001'
export const RURALPAYMENTS_API_NOT_FOUND_001 = 'RURALPAYMENTS_API_NOT_FOUND_001'
export const RURALPAYMENTS_API_ERROR_001 = 'RURALPAYMENTS_API_ERROR_001'
export const RURALPAYMENTS_API_ACCESS_DENIED_001 = 'RURALPAYMENTS_API_ACCESS_DENIED_001'

export const APIM_APIM_REQUEST_001 = 'APIM_APIM_REQUEST_001'
export const APIM_ACCESS_TOKEN_REQUEST_001 = 'APIM_ACCESS_TOKEN_REQUEST_001'

export const AUTHENTICATE_DATABASE_ALL_001 = 'AUTHENTICATE_DATABASE_ALL_001'
export const AUTHENTICATE_DATABASE_READ_001 = 'AUTHENTICATE_DATABASE_READ_001'
export const AUTHENTICATE_DATABASE_WRITE_001 = 'AUTHENTICATE_DATABASE_WRITE_001'
export const AUTHENTICATE_DATABASE_WRITE_002 = 'AUTHENTICATE_DATABASE_WRITE_002'

export const ENTRA_REQUEST_EMPLOYEE_LOOKUP_001 = 'ENTRA_REQUEST_EMPLOYEE_LOOKUP_001'
