/*
 *
 * Log codes
 * Format: <SERVICE NAME>_<LOG GROUP>_<LOG SUB GROUP>_<CODE>
 */

export const DAL_REQUEST_AUTHENTICATION_001 = 'DAL_REQUEST_AUTHENTICATION_001'
export const DAL_APPLICATION_REQUEST_001 = 'DAL_APPLICATION_REQUEST_001'
export const DAL_APPLICATION_RESPONSE_001 = 'DAL_APPLICATION_RESPONSE_001'
export const DAL_UNHANDLED_ERROR_001 = 'DAL_UNHANDLED_ERROR_001'
export const DAL_RESOLVERS_BUSINESS_001 = 'DAL_RESOLVERS_BUSINESS_001'
export const DAL_HEALTH_CHECK_001 = 'DAL_HEALTH_CHECK_001'
export const DAL_USER_REQUEST_001 = 'DAL_USER_REQUEST_001'

export const RURALPAYMENTS_API_REQUEST_001 = 'RURALPAYMENTS_API_REQUEST_001'
export const RURALPAYMENTS_API_NOT_FOUND_001 = 'RURALPAYMENTS_API_NOT_FOUND_001'
export const RURALPAYMENTS_API_ERROR_001 = 'RURALPAYMENTS_API_ERROR_001'
export const RURALPAYMENTS_API_ACCESS_DENIED_001 = 'RURALPAYMENTS_API_ACCESS_DENIED_001'
