"""
Represents the status of a business application.
"""
type BusinessApplicationStatus {
  """
  The unique identifier of the business application status.
  """
  id: ID

  """
  The open status of the business application.
  """
  open: String

  """
  The status of the business application.
  """
  status: String

  """
  The type of the business application.
  """
  type: String

  """
  The sector of the business application.
  """
  sector: String

  """
  The year of the business application.
  """
  year: Int

  """
  The FRN (Farm Reference Number) of the business application.
  """
  frn: String

  """
  The office of the business application.
  """
  office: String
}

"""
Represents a claim of a business application.
"""
type BusinessApplicationClaim {
  """
  The schema year of the business application claim.
  """
  schemaYear: Int

  """
  The type of the business application claim.
  """
  type: String

  """
  The status of the business application claim.
  """
  status: String

  """
  The last movement of the business application claim.
  """
  lastMovement: String
}

"""
Represents a business application.
"""
type BusinessApplication {
  """
  The status of the business application.
  """
  applicationStatus: BusinessApplicationStatus

  """
  The claim of the business application.
  """
  csClaim: BusinessApplicationClaim
}