"""
Represents the basic information of a business.
"""
type BusinessInfo {
  """
  The name of the business.
  """
  name: String

  """
  The reference of the business.
  """
  reference: String

  """
  The VAT number of the business.
  """
  vat: String

  """
  The address of the business.
  """
  address: Address

  """
  The phone details of the business.
  """
  phone: Phone

  """
  The email details of the business.
  """
  email: Email

  """
  The legal status of the business.
  """
  legalStatus: BusinessType

  """
  The type of the business.
  """
  type: BusinessType

  """
  The registration numbers of the business.
  """
  registrationNumbers: BusinessRegistrationNumbers
}

"""
Represents the registration numbers of a business.
"""
type BusinessRegistrationNumbers {
  """
  The Companies House number of the business.
  """
  companiesHouse: String

  """
  The Charity Commission number of the business.
  """
  charityCommission: String
}

"""
Represents the type of a business.
""" # eslint-disable-next-line @graphql-eslint/naming-convention
type BusinessType {
  """
  The code of the business type.
  """
  code: Int

  """
  The type of the business.
  """
  type: String
}

"""
Represents the a customer of a business.
"""
type BusinessCustomer {
  """
  The unique identifier of the customer.
  """
  customerId: ID

  """
  First name of the customer.
  """
  firstName: String

  """
  Last name of the customer.
  """
  lastName: String

  """
  The customer reference of the customer.
  """
  customerReference: String

  """
  The role the customer against the business.
  """
  role: String

  """
  The permissions the customer against the business.
  """
  permissions: [BusinessCustomerPermission]
}

type BusinessCustomerPermission {
  """
  The permission group id.
  """
  id: PermissionGroupId!

  """
  The permission group name.
  """
  name: String!

  """
  The permission group level assigned to the customer
  """
  level: PermissionLevel
}

"""
Represents a business.

Data Source: Rural Payments Portal (PRR)
"""
type Business {
  """
  The first unique identifier of the business.
  """
  businessId: ID #eslint-disable-line @graphql-eslint/no-typename-prefix
  """
  The Single Business Identifier (SBI) of the business.
  """
  sbi: ID!

  """
  The basic information of the business.
  """
  info: BusinessInfo

  """
  The land details of the business.
  """
  land: BusinessLand

  """
  The applications associated with the business.
  """
  applications: [BusinessApplication]

  """
  The CPH (County Parish Holding) numbers of the business.
  """
  cph: [CPH]

  """
  The customers associated with the business.
  """
  customers: [BusinessCustomer]
}
