"""
Common details for a business.
"""
type BusinessInfo {
  """
  Name of the business.
  """
  name: String

  """
  Firm Refererence Number (FRN) of the business.

  A unique 10-digit number that is known to the customer, for example, 1234567890.
  However a customer is more likely to be familiar with their Single Business Identified
  (SBI). FRN is commonly used in RPA's payment systems. The format is the same as the
  Customer Reference Number (CRN), which is also a 10-digit number.
  """
  reference: String

  """
  VAT number of the business.
  """
  vat: String

  """
  Trader number of the business.
  """
  traderNumber: String

  """
  Vendor number of the business.
  """
  vendorNumber: String

  """
  Address of the business.
  """
  address: Address

  """
  Telephone number of the business.
  """
  phone: Phone

  """
  Email address of the business.
  """
  email: Email

  """
  Legal status of the business. For example, Sole Proprietorship.
  """
  legalStatus: BusinessType

  """
  Type of the business.
  """
  type: BusinessType

  """
  Various registration numbers for the business. For example, Companies House number.
  """
  registrationNumbers: BusinessRegistrationNumbers
}

"""
Various registration numbers of the business.
"""
type BusinessRegistrationNumbers {
  """
  Companies House number of the business.
  """
  companiesHouse: String

  """
  Charity Commission number of the business.
  """
  charityCommission: String
}

"""
Type of the business represented by a code/description pair. For example, used for business type and legal status.
""" # eslint-disable-next-line @graphql-eslint/naming-convention
type BusinessType {
  """
  Code of the business type.
  """
  code: Int

  """
  Description of the business type.
  """
  type: String
}

"""
Customers/contacts of the business.
"""
type BusinessCustomer {
  """
  Interal SitiAgri/Portal unique identifier of the customer.
  """
  personId: ID @on

  """
  First name of the customer.
  """
  firstName: String @on

  """
  Last name of the customer.
  """
  lastName: String @on

  """
  Unique Customer Reference Number (CRN) of the customer. 10-digit number that should
  be known to to the customer, for example, 1234567890. This is the same format as the
  Firm Reference Number (FRN).
  """
  crn: String @on

  """
  Role the customer has for the business. For example, 'Owner', 'Agent', 'Employee'.
  """
  role: String @on

  """
  Permissions the customer has for the business.
  """
  permissionGroups: [ActivePermissionGroup] @on @excludeFromList
}

"""
Details for the business - 'business' and 'organisation' can be used interchangeably.
"""
type Business {
  """
  Internal SitiAgri/Portal unique identifier for the business.
  """
  organisationId: ID @on #eslint-disable-line @graphql-eslint/no-typename-prefix
  """
  Single Business Identifier (SBI) of the business.

  A unique 9-digit number that identifies the business. There is also the Firm Reference
  Number (FRN), a unique 10-digit number, that is less well known to customers.
  """
  sbi: ID! @on

  """
  Information of the business.
  """
  info: BusinessInfo

  """
  Land for the business.
  """
  land: BusinessLand @on

  """
  County Parish Holding (CPH) numbers of the business.
  """
  cphs: [CPH]

  """
  County Parish Holding (CPH) number of the business.
  """
  cph(number: String!): CPH

  """
  Customers associated with the business.
  """
  customers: [BusinessCustomer] @on

  """
  Customer associated with the business.
  """
  customer(crn: ID!): BusinessCustomer @on
}
