"""
County Parish Holding (CPH) number. It's a unique 9-digit identified for land
or buildings used to keep livestock and is used for tracking and managing
livestock movements to help prevent and control disease.

Data Source: SitiAgri

Note that Animal Plant and Health Agency (APHA) also have a source of CPH data.
While RPA issues the CPH number to the customer, APHA is interested in CPH
for disease control, therefore they may have more up-to-date and granular
information on species, for example.
"""
type CountyParishHolding {
  """
  CPH number. Consists of the county, the parish and the holding numbers.
  For example '10/327/0023'
  """
  cphNumber: ID @on

  """
  Parish associated with the CPH.
  """
  parish: String @on

  """
  Start date of the CPH.
  """
  startDate: Date @on

  """
  End date of the CPH.
  """
  endDate: Date @on

  """
  A comma-separated list of species associated with the CPH.
  For example, 'Cattle, Pigs'.

  Animal Plant and Health Agency (APHA) also have CPH data. APHA tend to hold more
  up-to-date information regarding species.
  """
  species: String @on

  """
  X Coordinate of the CPH.
  """
  xCoordinate: Int @on

  """
  Y Coordinate of the CPH.
  """
  yCoordinate: Int @on

  """
  Address
  """
  address: String @on
}
