"""
County Parish Holding (CPH).  Customers need a CPH for land or buildings
used to keep livestock or if the business uses animal by products. Used for
tracking and managing livestock movements to help prevent and control disease.

A business can have more than one CPH.

Data Source: SitiAgri

Note that Animal Plant and Health Agency (APHA) also have a source of CPH data.
While RPA issues the CPH number to the customer, APHA is interested in CPH
for disease control, therefore they may have more up-to-date and granular
information on species, for example.
"""
type CountyParishHolding {
  """
  CPH number. A 9-digit number, consisting of the county (2-digits), the parish
  (3-digits) and the holding (4-digits).  For example '12/345/6789'.

  The last 4-digits (e.g. 12/34/xxxx) indicate the type: 0001-4999 are
  standard CPHs. 7000-7999 are temporary. 8000-8999 are for non-agricultural
  holdings (e.g. livestock markets, meat product plants, seaports).
  """
  cphNumber: ID @on

  """
  Parish associated with the CPH.
  """
  parish: String @on

  """
  Start date of the CPH.
  """
  startDate: Date @on

  """
  End date of the CPH. If CPH is active, the date will be open ended. It will also be
  set for temporary CPHs.
  """
  endDate: Date @on

  """
  A comma-separated list of species associated with the CPH.
  For example, 'Cattle, Pigs'.

  Animal Plant and Health Agency (APHA) also have CPH data. APHA tend to hold more
  up-to-date information regarding species.
  """
  species: String @on

  """
  X Coordinate (Easting) of the centre of the CPH using the National Grid OSG836 datum.
  """
  xCoordinate: Int @on

  """
  Y Coordinate (Northing) of the centre of the CPH using the National Grid OSG836 datum.
  """
  yCoordinate: Int @on

  """
  Address of the land or correspondence address if issuing a temporary CPH. For
  common land, it should begin with 'CL @' followed by the common name and address.
  """
  address: String @on
}
