"""
X and Y co-ordinates for a CPH.
"""
type CPHCoordinate {
  """
  X value of the coordinate.
  """
  x: Int

  """
  Y value of the coordinate.
  """
  y: Int
}

"""
County Parish Holding (CPH) number. It's a unique 9-digit identified for land
or buildings used to keep livestock and is used for tracking and managing
livestock movements to help prevent and control disease.

Data Source: SitiAgri

Note that Animal Plant and Health Agency (APHA) also have a source of CPH data.
While RPA issues the CPH number to the customer, APHA is interested in CPH
for disease control, therefore they may have more up-to-date and granular
information on species, for example.
"""
type CPH {
  """
  CPH number. Consists of the county, the parish and the holding numbers, for example '10/327/0023'
  """
  number: String

  """
  Parcel numbers associated with the CPH.  This isn't always up-to-date.
  """
  parcelNumbers: [String]

  """
  Parish associated with the CPH.
  """
  parish: String @excludeFromList

  """
  Start date of the CPH.
  """
  startDate: Date @excludeFromList

  """
  Expiry (end) date of the CPH.
  """
  expiryDate: Date @excludeFromList

  """
  A list of species associated with the CPH. For example, 'Cattle', Pigs'.

  Animal Plant and Health Agency (APHA) also have CPH data. APHA tend to hold more
  up-to-date information regarding species.
  """
  species: [String] @excludeFromList

  """
  Coordinates of the CPH.
  """
  coordinate: CPHCoordinate @excludeFromList
}
