"""
A land parcel for a business.
When a change happens to a land parcel a new verion is created.
"""
type BusinessLandParcel {
  """
  Unique internal identifier of the land parcel.
  """
  id: ID! @on

  """
  Sheet ID of the land parcel, for example 'AB1234'
  """
  sheetId: String @on

  """
  Parcel ID of the land parcel, for example '1234'.
  """
  parcelId: String @on

  """
  Area (in hectares) of the land parcel.
  """
  area: Float @on

  """
  Indicates if a parcel has a pending Customer Notified Change (CNC).
  CNC could be a boundary change, parcel merge, split etc.
  """
  pendingDigitisation: Boolean @on

  """
  Date when this version of the land parcel finished.
  A date of 31/12/9999 indicates that this is the latest version of the parcel.
  """
  effectiveToDate: Date @on @excludeFromList

  """
  Date when this version of the land parcel came into effect.
  """
  effectiveFromDate: Date @on @excludeFromList
}

"""
Summary of the land parcels for a business.
"""
type BusinessLandSummary {
  """
  Area (in hectares) of arable land.
  """
  arableLandArea: Float @on

  """
  Area (in hectares) of permanent crops.
  """
  permanentCropsArea: Float @on

  """
  Area of permanent grassland.
  """
  permanentGrasslandArea: Float @on

  """
  Total area of land for the business (in hectares).
  """
  totalArea: Float @on

  """
  Total number of parcels for the business.
  """
  totalParcels: Float @on
}

"""
Land cover of a parcel for a business.
"""
type BusinessLandCover {
  """
  Unique internal identifier of the land cover.
  """
  id: ID! @on

  """
  Description of the land cover. For example, 'Arable Land', 'Permanent Grassland'
  """
  name: String @on

  """
  Area (in hectares) of the land cover.
  """
  area: Float @on

  """
  Internal code of the land cover. For example, '110' is the code for 'Arable Land'.
  """
  code: String @on

  """
  Indicates whether the land cover is Basic Payment Scheme (BPS) eligible.
  """
  isBpsEligible: Boolean @on
}

"""
Land details for a business.

Data Source: Land Management System (LMS)
"""
type BusinessLand {
  """
  Parcels of the business land for a particular date for a business.
  The earliest date is 01/01/2015.
  """
  parcels(date: Date): [BusinessLandParcel]
    @on
    @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR, SFI_REFORM])

  """
  A single parcel of the business land based on its SheetId and ParcelId for a
  particular date for a business.
  The earliest date is 01/01/2015.
  """
  parcel(date: Date, sheetId: ID!, parcelId: ID!): BusinessLandParcel @on

  """
  Land covers of a single parcel based on its SheetId and ParcelId for a particular
  date for a busines.
  The earliest date is 01/01/2015.
  """
  parcelCovers(date: Date, sheetId: ID!, parcelId: ID!): [BusinessLandCover] @on

  """
  Summary of the land for a particular date for a business.
  The earliest date is 01/01/2015.
  """
  summary(date: Date): BusinessLandSummary @on
}
