# TODO change to type and add other fields
scalar LandManagementParcels

type LandSummary {
  date: Date
  numberOfParcels: Numeric
  totalArea: Numeric
  mapImageData: Image
  permanentGrassland: Numeric
}

type LandManagement {
  parcels: LandManagementParcels

  summary: LandSummary
}

extend type Query {
  landManagement(businessId: ID!): LandManagement
}
