extend type Query {
  """
  Get a business by SBI (Single Business Identifier, a 9-digit number).
  """
  business(sbi: ID! @validateVariable(pattern: "^[1-9][0-9]{8}$")): Business
    @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR, SFI_REFORM])

  """
  Search for businesses by SBI, business name, or business postcode.
  """
  businessSearch(
    searchString: String!
    searchType: BusinessSearchFieldType!
    pagination: Pagination
  ): BusinessSearchResponse @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR, SFI_REFORM])
}
