"Represents data about mobile/landline details of a customer or business"
type Phone {
  """
  Mobile number of the customer or business
  """
  mobile: String @on

  """
  Landline number of the customer or business
  """
  landline: String @on
}

"Represents data about the email address of a customer or business"
type Email {
  """
  Email address of the customer or business
  """
  address: String @on

  """
  Validated status of the email address
  """
  validated: Boolean @on
}

"Represents data about the address details of a customer or business"
type Address {
  """
  PAF organisation name
  """
  pafOrganisationName: String @on

  """
  First line of a non-PAF address (maybe duplicated in the named fields, but not always)
  """
  line1: String @on

  """
  Second line of a non-PAF address (maybe duplicated in the named fields, but not always)
  """
  line2: String @on

  """
  Third line of a non-PAF address (maybe duplicated in the named fields, but not always)
  """
  line3: String @on

  """
  Fourth line of a non-PAF address (maybe duplicated in the named fields, but not always)
  """
  line4: String @on

  """
  Fifth line of a non-PAF address (maybe duplicated in the named fields, but not always)
  """
  line5: String @on

  """
  Building number range of the address
  """
  buildingNumberRange: String @on

  """
  Building name of the address
  """
  buildingName: String @on

  """
  Flat name of the address
  """
  flatName: String @on

  """
  Street of the address
  """
  street: String @on

  """
  Locality of the address
  """
  city: String @on

  """
  County of the address
  """
  county: String @on

  """
  Postal code of the address
  """
  postalCode: String @on

  """
  Country of the address
  """
  country: String @on

  """
  UPRN of the address
  """
  uprn: String @on

  """
  Dependant locality of the address
  """
  dependentLocality: String @on

  """
  Double dependant locality of the address
  """
  doubleDependentLocality: String @on

  """
  Type ID of the address
  """
  typeId: String @on
}

"""
Status of a customer or business record/account.
"""
type EntityStatus {
  """
  Indicates whether the customer or business account is locked.
  """
  locked: Boolean

  """
  Indicates whether the customer or business account has been confirmed.
  """
  confirmed: Boolean

  """
  Indicates whether the customer or business account has been deactivated.
  """
  deactivated: Boolean
}

"Represents data about a pagination details for a list of items"
input Pagination {
  """
  Number of items per page
  """
  perPage: Int!

  """
  Page number
  """
  page: Int!
}

enum AuthGroup {
  CONSOLIDATED_VIEW
  SINGLE_FRONT_DOOR
}
