type Phone {
  mobile: String
  landline: String
  fax: String
}

type Email {
  address: String
  validated: Boolean
  doNotContact: Boolean
}

type Address {
  pafOrganisationName: String
  buildingNumberRange: String
  buildingName: String
  flatName: String
  street: String
  city: String
  county: String
  postalCode: String
  country: String
  uprn: String
  dependentLocality: String
  doubleDependentLocality: String
  typeId: String
}
