"""
Basic information of a customer.
"""
type CustomerInfo {
  """
  Name of the customer.
  """
  name: CustomerName @on

  """
  Date of birth of the customer.
  """
  dateOfBirth: Date @on

  """
  Telephone number of the customer.
  """
  phone: Phone @on

  """
  Email address of the customer.
  """
  email: Email @on

  """
  Status of the customer record/account.
  """
  status: EntityStatus @on

  """
  Address of the customer.
  """
  address: Address @on

  """
  Do not contact status of the customer email address.
  """
  doNotContact: Boolean @on

  """
  Other IDs for this customer.
  """
  personalIdentifiers: [String] @on
}

"""
Full name of a customer.
"""
type CustomerName {
  """
  The title of the customer (e.g., Mr., Mrs., Dr.).
  """
  title: String @on

  """
  Any other title of the customer.
  """
  otherTitle: String @on

  """
  First name of the customer.
  """
  first: String @on

  """
  Middle names of the customer.
  """
  middle: String @on

  """
  Last name of the customer.
  """
  last: String @on
}

"""
Authenticate questions of the customer.

Data source: Rural Payments Portal

These are the memorable words (date, place, event) used to verify the
customer when they call the RPA. Originally, these were held in the
'Authenticate' system, but the data and functionality transferred to
the portal.
"""
type CustomerAuthenticationQuestions {
  """
  Memorable date response for the customer.
  """
  memorableDate: String @on

  """
  Memorable event response for the customer.
  """
  memorableEvent: String @on

  """
  Memorable place response for the customer.
  """
  memorableLocation: String @on

  """
  The date the record was last updated.
  """
  updatedAt: Date @on

  """
  Indicates whether the authenticate questions record was found for the customer.
  """
  isFound: Boolean @on
}

"""
Customer details.

Data source: Rural Payments Portal
"""
type Customer {
  """
  Internal SitiAgri/Portal unique identifier of the customer.
  """
  personId: ID! @on #eslint-disable-line @graphql-eslint/no-typename-prefix
  """
  Customer Reference Number (CRN) of the customer. Unique 10-digit number used
  to identify the customer. The customer should know their CRN, although their
  Single Business Identifier (SBI) for their business is more commonly quoted.
  """
  crn: ID! @on

  """
  Basic information of the customer.
  """
  info: CustomerInfo @on

  """
  Security questions (memorable words) of the customer.
  """
  authenticationQuestions: CustomerAuthenticationQuestions
    @on
    @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR])

  """
  Businesses associated with the customer.
  """
  businesses: [CustomerBusiness] @on

  """
  A single business filtered by the businesses using Single Business Identifier (SBI) associated with the customer.
  """
  business(sbi: ID!): CustomerBusiness @on
}

"""
A business associated with the customer.
"""
type CustomerBusiness {
  """
  Internal SitiAgri/Portal unique identifier of the customer.
  """
  organisationId: ID @on

  """
  Single Business Identifier (SBI) of the business. A unique 9-digit identifier
  for the business.
  """
  sbi: ID! @on

  """
  Name of the business.
  """
  name: String! @on

  """
  Role that the customer has for the business.
  """
  role: String @on

  """
  Messages for the customer for the business. These message are those shown in the
  Rural Payments Portal, and not any correspondence the customer may have had with
  the Rural Payments Agency (RPA).

  Retrieves messages from fromDate to today if provided; otherwise, returns all messages.
  - fromDate: Optional. Include messages on or after this date up to the current date.
  """
  messages(fromDate: Date): [CustomerBusinessMessage] @on @excludeFromList

  """
  Permission groups for the customer for the business.
  """
  permissionGroups: [ActivePermissionGroup] @on @excludeFromList
}
