type CustomerInfo {
  name: CustomerName
  dateOfBirth: String
  phone: Phone
  email: Email
  status: CustomerStatus
  address: Address
}

type CustomerName {
  title: String
  otherTitle: String
  first: String
  middle: String
  last: String
}

type CustomerStatus {
  locked: Boolean
  confirmed: Boolean
  deactivated: Boolean
}

type CustomerAuthenticationQuestions {
  memorableDate: String
  memorableEvent: String
  memorablePlace: String
}

type Customer {
  id: ID!
  info: CustomerInfo
  authenticationQuestions: CustomerAuthenticationQuestions
  businesses: [CustomerBusiness]
}

type CustomerBusiness {
  id: ID!
  name: String!
  sbi: Int!
  roles: [String]
  privileges: [String]
}
