"""
Represents a message related to a customer's business.

Data Source: Rural Payments Portal (PRR)
"""
type CustomerBusinessMessage {
  """
  The unique identifier of the message.
  """
  id: ID! @on

  """
  The subject of the message.
  """
  subject: String @on

  """
  The date of the message.
  """
  date: Date @on

  """
  The body content of the message.
  """
  body: String @on

  """
  Whether the message has been read.
  """
  read: Boolean @on

  """
  Whether the message has been deleted.
  """
  deleted: Boolean @on
}
