extend type Mutation {
  updateCustomerAddress(input: UpdateCustomerAddressInput!): UpdateCustomerResponse
    @auth(requires: [SINGLE_FRONT_DOOR])
  updateCustomerDateOfBirth(input: UpdateCustomerDateOfBirthInput!): UpdateCustomerResponse
    @auth(requires: [SINGLE_FRONT_DOOR])
  updateCustomerEmail(input: UpdateCustomerEmailInput!): UpdateCustomerResponse
    @auth(requires: [SINGLE_FRONT_DOOR])
  updateCustomerName(input: UpdateCustomerNameInput!): UpdateCustomerResponse
    @auth(requires: [SINGLE_FRONT_DOOR])
  updateCustomerPhone(input: UpdateCustomerPhoneInput!): UpdateCustomerResponse
    @auth(requires: [SINGLE_FRONT_DOOR])
  updateCustomerDoNotContact(input: UpdateCustomerDoNotContactInput!): UpdateCustomerResponse
    @auth(requires: [SINGLE_FRONT_DOOR])
}

input UpdateCustomerAddressInput {
  """
  Customer Reference Number (CRN) of the customer. Unique 10-digit number used
  to identify the customer.
  """
  crn: ID!
  """
  Address of the customer.
  """
  address: AddressInput!
}

input UpdateCustomerDateOfBirthInput {
  """
  Customer Reference Number (CRN) of the customer. Unique 10-digit number used
  to identify the customer.
  """
  crn: ID!
  """
  Date of birth of the customer (YYYY-MM-DD).
  """
  dateOfBirth: Date!
}

input UpdateCustomerNameInput {
  """
  Customer Reference Number (CRN) of the customer. Unique 10-digit number used
  to identify the customer.
  """
  crn: ID!
  """
  First name of the customer.
  """
  first: String
  """
  Last name of the customer.
  """
  last: String
  """
  Middle names of the customer.
  """
  middle: String
  """
  The title of the customer (e.g., Mr., Mrs., Dr.).
  """
  otherTitle: String
  """
  The title of the customer (e.g., Mr., Mrs., Dr.).
  """
  title: String
}

input UpdateCustomerEmailInput {
  """
  Customer Reference Number (CRN) of the customer. Unique 10-digit number used
  to identify the customer.
  """
  crn: ID!
  """
  Email address of the customer.
  """
  email: EmailInput!
}

input UpdateCustomerPhoneInput {
  """
  Customer Reference Number (CRN) of the customer. Unique 10-digit number used
  to identify the customer.
  """
  crn: ID!
  """
  Telephone number of the customer.
  """
  phone: PhoneInput!
}

input UpdateCustomerDoNotContactInput {
  """
  Customer Reference Number (CRN) of the customer. Unique 10-digit number used
  to identify the customer.
  """
  crn: ID!
  """
  Do not contact status of the customer email address.
  """
  doNotContact: Boolean!
}

type UpdateCustomerResponse {
  success: Boolean
  customer: Customer
}
