extend type Query {
  """
  Get a customer by CRN (Customer Reference Number, a 10-digit number).
  """
  customer(crn: ID! @validateVariable(pattern: "^[1-9][0-9]{9}$")): Customer
    @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR, SFI_REFORM])

  """
  Search for customers by CRN, personal identifier, customer name, customer postcode,
  vendor number, or trader number.
  """
  customerSearch(
    searchString: String!
    searchType: CustomerSearchFieldType!
    pagination: Pagination
  ): CustomerSearchResponse @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR, SFI_REFORM])
}
