extend type Query {
  customer(crn: ID!): Customer @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR, SFI_REFORM])

  """
  Search for customers by CRN, personal identifier, customer name, customer postcode,
  vendor number, or trader number.
  """
  customerSearch(
    searchString: String!
    searchType: CustomerSearchFieldType!
    pagination: Pagination
  ): CustomerSearchResponse @auth(requires: [CONSOLIDATED_VIEW, SINGLE_FRONT_DOOR, SFI_REFORM])
}
