"""
The field to search customers by.
"""
enum CustomerSearchFieldType {
  """
  The full 10-digit Customer Reference Number (CRN); returns 0 or 1 results.
  """
  CRN

  """
  The full personal identifier, at least 9 characters; returns 0 or 1 results.
  """
  PERSONAL_IDENTIFIER

  """
  A partial last name, at least 3 characters; returns 0 or more results.
  """
  CUSTOMER_NAME

  """
  A full customer postcode, at least 5 characters; returns 0 or more results.
  """
  CUSTOMER_POSTCODE

  """
  At least the first 6 characters of the vendor number; returns 0 or more results.
  """
  VENDOR_NUMBER

  """
  At least the first 6 characters of the trader number; returns 0 or more results.
  """
  TRADER_NUMBER
}

"""
Summary details of a customer returned by a customer search.
"""
type CustomerSearchResult {
  """
  Internal SitiAgri/Portal unique identifier of the customer.
  """
  personId: ID

  """
  Customer Reference Number (CRN) of the customer.
  """
  crn: ID

  """
  Full name of the customer.
  """
  fullName: String

  """
  Primary address of the customer.
  """
  address: Address

  """
  Other IDs for this customer.
  """
  personalIdentifiers: [String]

  """
  National Insurance number of the customer.
  """
  nationalInsuranceNumber: String

  """
  Email address of the customer.
  """
  email: String

  """
  The status of the customer record/account.
  """
  status: EntityStatus
}

"""
A page of customer search results.
"""
type CustomerSearchResponse {
  """
  The customers matching the search.
  """
  results: [CustomerSearchResult]

  """
  Paging information for the search results.
  """
  pageInfo: PageInfo
}
